# Generated by Django 5.0.4 on 2024-04-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='India', max_length=200),
            preserve_default=False,
        ),
    ]
